### ISSUE TITLE
bootstrapHighlightClasses option doesn't seem to work

### ISSUE THREAD

**Issue by ronaldaug** [vadikom/smartmenus#100]
I found that there are two classes "text-dark bg-light" always inject via smartmenu script.
I try to reset these classes with two methods as below but it doesn't work.

### 1 - **JS**
```javascript
$(function(){
    $("#main-menu").smartmenus({
         bootstrapHighlightClasses:''
    })
})
```

### 2 - **data-sm-options**
```html
 <nav data-sm-options="{bootstrapHighlightClasses:''}" class="navbar navbar-expand-lg navbar-light bg-light">
```

[Codepen Demo link](https://codepen.io/ronaldaug/pen/KKKxBBv)

### Screenshot
<img width="685" alt="Screen Shot 2019-11-14 at 4 21 40 PM" src="https://user-images.githubusercontent.com/33022876/68846628-c4691380-06fb-11ea-8f67-d1def6e60f98.png">

**Comment by vadikom** [comment]
Hi!

The `data-sm-options` attribute needs to be added to the root `<ul>` element - not to the `<nav>` element - e.g. try the following:

```html
<ul class="nav navbar-nav mr-auto" data-sm-options="{ bootstrapHighlightClasses: '' }">
```

and it should work.

Cheers!
