### ISSUE TITLE
Text blurry in Chrome on scroll down to bottom

### ISSUE THREAD

**Issue by myozawlatt** [vadikom/smartmenus#101]
Texts are blur on sub menus when scrolled down to bottom. It occurs only on Chrome browser. 
![smrtmuerror](https://user-images.githubusercontent.com/20241314/69128351-7dec2e00-0ada-11ea-8b6b-17f6704d7930.png)

**Comment by vadikom** [comment]
Hmm, I am not able to reproduce this on the default demos (tested on Mac and Windows 7). Could you please provide some test URL?
