### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by gtbu** [vadikom/smartmenus#106]
Many modern menus use the hamburger for a narrow sidebar instead of a dropdown in narrow mode.
Is there a way to to this with smartmenus. Evtl. You can expand the examples or a pen ?

**Comment by vadikom** [comment]
Hi, yep, of course, it is possible. It's just a matter of styling the main menu container appropriately on small screens. Here are a couple of demos I created for a recent customer:

1) Dropdowns on desktop, off-canvas sidebar on mobile:
https://codepen.io/vadikom/pen/qLXYaE

2) Permanent sidebar on desktop, off-canvas sidebar on mobile:
https://codepen.io/vadikom/pen/rNBZYWO

I have it in my TODO list to prepare more generic example and publish them on the site but, unfortunately, that list is way too long for now. :(

**Comment by gtbu** [comment]
The https://codepen.io/vadikom/pen/qLXYaE is quite near - just the sidebar should always be invisible. For sticky exists a very flexible  jquery.stickybits.js
