### ISSUE TITLE
Bootstrap 5 addon

### ISSUE THREAD

**Issue by elemis** [vadikom/smartmenus#107]
Are there any plans for Bootstrap 5 addon? 

Just recently tried switching to BS5 and started getting the error "TypeError: Attempted to assign to readonly property." which points to the lines below from "Bootstrap 4 Addon - v0.1.0":

`}), o.length && !r.SmartMenus.Bootstrap.keydownFix && (r(document).off("keydown.bs.dropdown.data-api", ".dropdown-menu"), r.fn.dropdown && r.fn.dropdown.Constructor && r(document).on("keydown.bs.dropdown.data-api", ".dropdown-menu.show", r.fn.dropdown.Constructor._dataApiKeydownHandler), r.SmartMenus.Bootstrap.keydownFix = !0)`

**Comment by vadikom** [comment]
As far as I can see, Bootstrap 5 doesn't require jQuery any more. And this error seems to occur if you have jQuery included before the Bootstrap 5 alpha JS "bootstrap.min.js". Although I haven't investigated in details, I suspect their current alpha code overwrites some jQuery functionality.

To avoid the issue try including jQuery after "bootstrap.min.js" but still before "jquery.smartmenus.js" and "jquery.smartmenus.bootstrap-4.js" and let me know if you still have any troubles.

**Comment by lsblsb** [comment]
first - thanks for your great work.

i also tried the solutions at #134, but in the mobile view the hamburger navigation does still not work.
With your fixes i do not get the 'guid' error, but the hamburger navigation does not work.
In the desktop view the navigation works fine though.
