### ISSUE TITLE
Menu Z Index question.

### ISSUE THREAD

**Issue by kathadris** [vadikom/smartmenus#185]
I love this nav system to start. But I am working on a page with a popup gallery. On the first image the drop down works perfect. But the second image with the gallery open it stays on top. Is there anyway to not show while the gallery is open? Thanks for your help and work even if it cant be done. Gallery is done using fancybox.

https://pasteboard.co/Kb0sRFatdHZz.png
https://pasteboard.co/pRODMRcLMPIq.png

**Comment by vadikom** [comment]
Hi, the default z-index the script uses is 9999 (defined in "sm-core-css.css"). I am not sure what is the exact z-index of the gallery script you use but you could try something like this and see if it solves the issue (just add it in some of your stylesheets):
```css
#main-menu {
    z-index: 1;
}
```
If you still have any troubles, please post an URL to some kind of live demo and I will check it.

Cheers!

**Comment by kathadris** [comment]
Thank You so much. Adding the main-menu z-index 1 fixed my issue. Nav is now above the images but behind the pop-up gallery. Thank you again for your help.
