### ISSUE TITLE
A11y: menu toggle button needs a :focus halo

### ISSUE THREAD

**Issue by jenlampton** [vadikom/smartmenus#195]
Hello and thank you again for this fantastic library. 

I am once again trying to make the navigation experience as accessible as possible. I received some feedback that our menu toggle button does not receive the appropriate `:focus` halo when tabbing through the page on mobile. A sighted user navigating our site with the keyboard can't see when the hamburger menu is active, so they don't know when they can use the spacebar to open the menu to see items within.

I can see this problem on https://www.smartmenus.org also.

Some quick research shows that `label` is not a focusable element, but there are some recommendations on how to get the label to respond to a nearby input on [stack exchange](https://stackoverflow.com/questions/5978239/anyway-to-have-a-label-respond-to-focus-css#:~:text=Have%20the%20label%20element%20follow,%7B%7D%20to%20target%20the%20label.).

We're going to give this a try. If it works, would you be open to making a similar change to the library in a future release?

**Comment by vadikom** [comment]
You could now give the following solution a try if you like:

https://github.com/vadikom/smartmenus/issues/137#issuecomment-1235380517

The toggle button should be focusable and also work just fine when JS support is disabled.

**Comment by jenlampton** [comment]
Great, I'll close this issue in favor of that solution.
