### ISSUE TITLE
re-initialization of Bootstrap addon

### ISSUE THREAD

**Issue by clayzermk1** [vadikom/smartmenus#26]
I use Backbone.js/Marionette.js for a MV* framework. They use Javascript to dynamically render HTML content. I also use Bootstrap.

I have found that if I re-render my navbar view the SmartMenus Bootstrap addon ceases to function. One look at the addon js file makes it clear that the addon is initialized at the time of invocation (the DOM isn't ready in my case). As a workaround, I have copy/pasted the addon initialization code into my view's `onDomRefresh` event handler in order to re-initialize the addon. For some reason re-invoking the addon js file at that point doesn't work either.

What are the best practices for applying the addon in this sort of situation? Would you be open to exposing the initialization of the addon on `$.SmartMenus.prototype`? I would be happy to provide a PR.

Thank you for your time and such a nice product :beers:!

**Comment by vadikom** [comment]
Hi and thanks very much for your input! :thumbsup:

Indeed, in the current version the addon is initialized just once ondomready and any navbars that are added in the DOM dynamically after that won't be initialized. So it really makes sense to rework the addon and expose some init method that could be called at any time. I will try to do this in the next few days and will post back. Stay tuned..

**Comment by clayzermk1** [comment]
That'd be great! Thank you so much.

**Comment by vadikom** [comment]
OK, I just committed the updates. You can grab the code from here (note that the core also needed some changes so it's a good idea to use the updated one below to avoid any issues):

https://raw.githubusercontent.com/vadikom/smartmenus/master/src/addons/bootstrap/jquery.smartmenus.bootstrap.js
https://raw.githubusercontent.com/vadikom/smartmenus/master/src/jquery.smartmenus.js

All updates will be included in the next release so you don't need to worry about upgrading in the future.

You can now call <code>$.SmartMenus.Bootstrap.init()</code> when your navbar is available in the DOM. It's not a problem to call it multiple times, it will only handle navbars that are still not initialized.

Note that the following methods might also be handy (you can use them just fine with the Bootstrap addon, just set some id to your <code>ul.navbar-nav</code> so you can call them for it):

http://www.smartmenus.org/docs/#refreshInstance
http://www.smartmenus.org/docs/#destroyInstance

**Comment by clayzermk1** [comment]
FYI, the dists look like they weren't built for the last commit.

**Comment by clayzermk1** [comment]
Tested, works like a champ for me! Thank you again! :beers:

**Comment by vadikom** [comment]
Np at all! This will surely be useful to others so I really appreciate your input!

I only build the dists for new versions and I have planned some other fixes too for the new release so it will wait for now (that's why I pointed you to the "src" folder).

OK, I'm closing this.. Cheers!
