### ISSUE TITLE
Uncaught TypeError: Cannot set property 'Bootstrap' of undefined

### ISSUE THREAD

**Issue by faizplus** [vadikom/smartmenus#28]
Menu dropdown is not working and in console i get the following error

<code>Uncaught TypeError: Cannot set property 'Bootstrap' of undefined</code>

on line 14

**Comment by vadikom** [comment]
Sorry for the late reply, it's been very hectic here lately!

Make sure you've linked correctly the SmartMenus script core `jquery.smartmenus.js.js` file on your page before the Bootstrap addon `jquery.smartmenus.bootstrap.js`.

**Comment by bAlAAA** [comment]
Thanks vadikom works fine
