### ISSUE TITLE
Npm + Webpack

### ISSUE THREAD

**Issue by matiux** [vadikom/smartmenus#29]
Is there a way to use it with webpack and npm?

**Comment by vadikom** [comment]
There is no published npm package for now (1.0.0 final will be available as a npm package). So you could use the bower package at the moment if you like:

for v0.9.7:
`bower install smartmenus`

for v1.0.0-beta1:
`bower install smartmenus#1.0.0-beta1`

The following might be useful if you decide to use the bower package with Webpack:
http://webpack.github.io/docs/usage-with-bower.html

**Comment by vadikom** [comment]
As of v1.0.0 the plugin is available via npm.
