### ISSUE TITLE
Round corner highlight of submenu in sm-blue theme

### ISSUE THREAD

**Issue by georgema1982** [vadikom/smartmenus#30]
I find a UI bug in sm-blue theme. If the last main menu item (aka the rightmost main menu item) has submenu items, the highlight of the last submenu item (aka the bottom one) has round corner at the bottom. Please see the screenshot below:

![sm-blue-bug](https://cloud.githubusercontent.com/assets/727970/9595718/342554bc-5027-11e5-8649-aae19302e34e.png)

**Comment by vadikom** [comment]
Yep, I am aware of it but thanks very much for reporting it nonetheless!

It will be fixed in the next release.

Cheers!
