### ISSUE TITLE
Stable 1.0.0 version on CDNJS.com?

### ISSUE THREAD

**Issue by holtkamp** [vadikom/smartmenus#31]
While it seems only a [beta version is tagged](https://github.com/vadikom/smartmenus/tree/1.0.0-beta1), it seems that [CDNJS](https://cdnjs.com/libraries/jquery.smartmenus) has already picked up a stable ```1.0.0``` version. How is this possible?

**Comment by vadikom** [comment]
As far as I can see, they've got the beta1:
https://cdnjs.cloudflare.com/ajax/libs/jquery.smartmenus/1.0.0/jquery.smartmenus.js

Note sure why, maybe their system doesn't recognise beta releases on GitHub. Anyway, 1.0.0 final is coming very soon (hopefully within 2-3 weeks) but it's definitely still not released.

**Comment by holtkamp** [comment]
ok, thanks for the swift clarification, strange thing is that they **also** host the beta (use the selector):
https://cdnjs.com/libraries/jquery.smartmenus/1.0.0-beta1

Closing issue
