### ISSUE TITLE
Menu HTML structure doesn't allow any customizations

### ISSUE THREAD

**Issue by FlyingDR** [vadikom/smartmenus#33]
Currently (in v0.9.7) script expects submenu to be in ```<ul>``` element that is immediate child of its parent. Hence any attempts to put something else in submenu fails as it may require additional elements between parent menu item and its submenu.

For example in one of my projects I need to put images in submenu together with submenu items, but found no way to do it since attempt to wrap submenu in additional ```<div>``` breaks script.

It may be good solution to allow passing CSS selectors for searching for submenus as configuration option as, for example, [slick slider](https://kenwheeler.github.io/slick/) does.

**Comment by ginsterbusch** [comment]
So what you are trying to say is, when you create a structure like this:

```html
<div class="my-menu">
<ul>
<li><div class="my-submenu">
<ul>
<li><a href="#">Item 1</a></li>
<li><a href="#">Item 2</a></li>
...
</ul></div></li>
</div>
```

.. then the script falls apart?

Cause I had some hard time understanding your text.

cu, w0lf.

**Comment by FlyingDR** [comment]
Sorry for that, I would need to add better example. 

Yes, it is exactly what I mean, in a case if submenu is not a simple ```<ul>```, but additionally wrapped in ```<div>``` - I get JavaScript error: ```TypeError: par.parentNode is null``` in [this line](https://github.com/vadikom/smartmenus/blob/0.9.7/dist/jquery.smartmenus.js#L640). Additionally there is multiple ```TypeError: Cannot read property 'css' of null``` errors in [this place](https://github.com/vadikom/smartmenus/blob/0.9.7/dist/jquery.smartmenus.js#L381), but it seems to be consequences of previous error.

However I've just realized that there is newer version (0.9.7 is what came from Bower install), I will check with latest 1.0.0-beta and will let you know.

**Comment by FlyingDR** [comment]
Error is same, located [here](https://github.com/vadikom/smartmenus/blob/master/dist/jquery.smartmenus.js#L676)

**Comment by vadikom** [comment]
Yes, that's a requirement for now - i.e. you need to nest the sub UL element directly in the parent item's LI element. Are you sure there is no way to structure properly your HTML code if you follow this rule? Could you please post some sort of sample (demo URL would be best)?

**Comment by FlyingDR** [comment]
Here is actual example from the project, I'm currently working on:
![menu](https://cloud.githubusercontent.com/assets/822673/11192157/787c1892-8cb0-11e5-8ce3-95f706d34f20.jpg)
as you can see - submenu block contains not only menu items, but also several images. I've tried to imagine how to implement it using single ```<ul>``` without additional wrapper but found no solution. Hence I decide that it may be good idea for improvement for this, actually very good, product.

**Comment by ginsterbusch** [comment]
So he's doing what I already suspected - trying to use smartmenus.js for a mega dropdown.
Which would indeed be cool ;)

cu, w0lf.

**Comment by vadikom** [comment]
It's not a problem to create a mega drop-down with whatever HTML you like inside. You just need to use the proper structure supported by the script - here is a sample mega dropdown sub menu (a live sample is also included in the default demo in the download package):

```html
  ...
  <li><a href="#">Jewelry &amp; Watches</a>
    <ul class="mega-menu">
      <li>
        <!-- The mega drop down contents - put whatever HTML you like here -->
      </li>
    </ul>
  </li>
  ...
```
So inside that mega drop-down you could include more lists of links, images, columns whatever you like.

Here is also a topic in the forums with some sample code that creates columns of links inside a mega drop-down:

http://www.smartmenus.org/forums/topic/mega-drop-down/

**Comment by FlyingDR** [comment]
Thank you for advice, I will try it. Closing this issue for now.
