### ISSUE TITLE
Highlight and showOnClick problem

### ISSUE THREAD

**Issue by lcamozzi** [vadikom/smartmenus#38]
If showOnClick is enabled, when you click on a menu item (in desktop mode, not collapsed) the item becomes highlighted and its color changes accordingly, but if you move the mouse on another menu element, the first item remains highlighted until you click somewhere on the page.
![schermata 2016-01-12 alle 17 47 36](https://cloud.githubusercontent.com/assets/8394081/12269986/43ac8ce8-b954-11e5-91dc-630327d963cd.png)

**Comment by vadikom** [comment]
Hm, you are right, seems to be a bug introduced in 1.0.0-beta1. I will investigate it ASAP..

Thanks very much for your input!

**Comment by vadikom** [comment]
The fix will make it into 1.0.0. If you need it sooner, you can grab the code directly from GitHub:

https://raw.githubusercontent.com/vadikom/smartmenus/master/src/jquery.smartmenus.js

Cheers!

**Comment by lcamozzi** [comment]
Thank you!

Luca


Il giorno 14/gen/2016, alle ore 09:48, Vasil Dinkov <notifications@github.com> ha scritto:
