### ISSUE TITLE
False Selection Indicator Bug (Focus Bug)

### ISSUE THREAD

**Issue by tpaluch** [vadikom/smartmenus#41]
Here is how to reproduce the bug:
1) Right-Click on Navigation Dropdown
2) Left-Click on any Dropdown Element
3) Hover over any other Dropdown Element

As you can see, the left-clicked element remains 'focused' despite not being selected/hovered. 

You can also reproduce this bug by:
1) Right-Clicking any Dropdown Element
2) Left-Clicking any Dropdown Element
3) Hover over any other Dropdown Element

**Comment by vadikom** [comment]
Please check again with the latest dev version from Github:

https://raw.githubusercontent.com/vadikom/smartmenus/master/src/jquery.smartmenus.js

There was a fix committed recently for a similar issue. If you are still having troubles, please let me know which exact browser/version you are testing with.

Thanks!

**Comment by tpaluch** [comment]
Thanks! That worked. I hate to do this but I had trouble logging into your website... the password wasn't working... it was asking me to sign into wordpress?? I have an extra question: Why do my submenues open on the left side instead of on the right like they traditionally do? For example, on your website if you go to About > The Company > ... it expands to the right. Mine is the opposite and it goes to the left. I am using it with Bootstrap 3. I am not using pull-left, and i tried pull-right but that did not fix the issue.

**Comment by tpaluch** [comment]
Thanks, that worked!
