### ISSUE TITLE
Submenus opening on left side

### ISSUE THREAD

**Issue by tpaluch** [vadikom/smartmenus#42]
When I hover over a menu, it opens on the left side instead of on the right... I'm not sure why. I am using Bootstrap 3 and no pull-right/left classes.

**Comment by vadikom** [comment]
This could happen if your `.navbar-nav` UL has the `navbar-right` class. If you need that class, then you can use the `data-sm-reverse` attribute for any sub menu:

http://www.smartmenus.org/docs/#data-sm-reverse

Let me know if you still have any troubles.

**Comment by tpaluch** [comment]
That worked, thanks!
