### ISSUE TITLE
right to left by code

### ISSUE THREAD

**Issue by webineh** [vadikom/smartmenus#44]
hellow and thank you for smartmenu

i need use in it right to left by code  please help me.

**Comment by vadikom** [comment]
Hi, please check the docs:
http://www.smartmenus.org/docs/#rtl

The default demo page also includes the "Right-to-left" checkbox in the "Switch theme" panel that will produce sample code below when you check it.

And please note that this is an issue/bug tracker so in the future if you have any support queries, please post them in the forums:

http://www.smartmenus.org/forums/

**Comment by webineh** [comment]
very thanks Work Great
