### ISSUE TITLE
mobile menu not working..

### ISSUE THREAD

**Issue by rrabik** [vadikom/smartmenus#45]
Hi,
I downloaded Smartmenus from http://www.smartmenus.org/download/.
When I locally view "smartmenus-1.0.0/demo/index.html" on maximized firefox or IE, the horizontal menu works fine. But when I decrease the size of the browser, the menu does not change to mobile menu. What I mean is I don't see  that 3 lined box. But the menu does change to vertical menu. What am I missing here?
What do I have to do to view 3 small horizontal lines used in mobile menu?

**Comment by rrabik** [comment]
this is what I mean. Decrease the size of the browser and mobile menu is not activated.
http://codepen.io/vadikom/pen/rVMmMm?editors=0110

**Comment by vadikom** [comment]
You can follow this tutorial to add a mobile menu toggle button:

http://www.smartmenus.org/docs/#menu-toggle-button

And please note that this is an issue/bug tracker so in the future if you have any support queries, please post them in the forums:

http://www.smartmenus.org/forums/
