### ISSUE TITLE
Uncaught TypeError: Cannot set property 'Bootstrap' of undefined

### ISSUE THREAD

**Issue by tpaluch** [vadikom/smartmenus#47]
Uncaught TypeError: Cannot set property 'Bootstrap' of undefined
(anonymous function) @ jquery.smartmenus.bootstrap.min.js:3
(anonymous function) @ jquery.smartmenus.bootstrap.min.js:3
(anonymous function) @ jquery.smartmenus.bootstrap.min.js:3

I have jquery.smartmenus.bootstrap.min and jquery.smartmenus.bootstrap

Non-minified js gives: 
jquery.smartmenus.bootstrap.js:24 Uncaught TypeError: Cannot set property 'Bootstrap' of undefined

I am using Version 1.0.0 from your website.

**Comment by vadikom** [comment]
Make sure `jquery.smartmenus.min.js` is also included in the page source before `jquery.smartmenus.bootstrap.min.js` and let me know if you still have any troubles.
