### ISSUE TITLE
Having issue when toggle on sub menu in Mobile.

### ISSUE THREAD

**Issue by osamasabir** [vadikom/smartmenus#48]
having issue when click on sub-menu 

like 3rd level of menu when i toggle 3rd level it toggle all the level :( why is it like that ? 

but when i click on sub-arrow it is working fine... but when i click in the middle :-1:  it toggle my parent level as well 
![sub-menu-problem](https://cloud.githubusercontent.com/assets/17942396/17324638/f2de0e56-58c0-11e6-8a7e-2d05c31525bf.jpg)

when i click between the highlighted area.. (as show in attached file). it toggles parent as well.

![sub-menu-working-fine](https://cloud.githubusercontent.com/assets/17942396/17324694/2755c4b2-58c1-11e6-94ba-6a2191f5af7e.jpg)

when i click arrows.. (as show in attached file). it toggles only the element not its parent.

please let me know how to fix it..

**Comment by osamasabir** [comment]
Anyone ? there ??

**Comment by vadikom** [comment]
Here is some info about the default behavior and how you could change it with some additional code:

http://www.smartmenus.org/forums/topic/mobile-menu-top-level-menu-items-as-links/#post-3233

In the future please post similar questions in the forums (we prefer to use the GitHub issues tracker just for bugs).

Thanks!
