### ISSUE TITLE
Unable to open a link on sub-menu on touch device

### ISSUE THREAD

**Issue by elonart** [vadikom/smartmenus#52]
Hello,
Because of unable to use mouse hover on touch device, I set smartmenus like this.
$(‘.sm’).smartmenus({
noMouseOver : true, //disable mouse hover.
showFunction : function($ul, complete) {
$ul.slideDown(250, complete);
},
hideFunction : function($ul, complete) {
$ul.slideUp(250, complete);
}
});
And I use double click event to open link on sub-menu. It works fine on chrome, but not on IE and Siri. Please help me to solve this bug.

**Comment by vadikom** [comment]
Please post some kind of online demo (e.g. create one on https://jsfiddle.net/) so that I could test your code.

And in the future please post similar support questions in the forums http://www.smartmenus.org/forums/ . We prefer to use the Github issue tracker just for bugs in the core script functionality.

Thanks!

**Comment by elonart** [comment]
Dear Vasil


I posted demo to this link. Please help me to solve the issue.


https://jsfiddle.net/elonart/6z365jr8/

Edit fiddle - JSFiddle<https://jsfiddle.net/elonart/6z365jr8/>
jsfiddle.net
Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor.





Dang Quang Hieu


________________________________

**Comment by elonart** [comment]
Sorry, the correct link is https://jsfiddle.net/elonart/6z365jr8/2/

**Comment by vadikom** [comment]
Thanks, I took a look. I still don't understand what exactly is not working for you in IE (which IE version?) and Siri (how do you test in Siri?)? Please try to explain step by step what you are doing and expect to happen.

But I get the feeling you have misunderstood how the script works so a quick note - you don't need to use specifically "noMouseOver : true" on small screens - the script will automatically detect touch input and act accordingly. This option is provided just in case someone wants to mimic touch screen device behavior even in desktop non-touch mode.

**Comment by elonart** [comment]
Dear Vasil,

It's not working for IE11 and Safari (not Siri. Sorry). I test on smartphone.
I explain my expect.
1. For devices which support hover (Ex: PC):
*When hover on menu's element, it'll expand submenu. 
*When click on menu's element, it'll open the url (href) of that element.
2. For devices which not support hover (Ex: smartphone):
*When click on menu's element, it'll expand submenu. 
*When double click on menu's element, it'll open the url (href) of that element.

Please help me to solve my expect.
Best regards,

**Comment by vadikom** [comment]
Sorry, but I still don't get it - the way you describe it, is exactly the way the script currently works by default. Please test this page on desktop/mobile and let me know what exactly you don't like:

http://vadikom.github.io/smartmenus/src/demo/
