### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by ufhy** [vadikom/smartmenus#56]
how to use destroy method ?
```
$('#main-menu').smartmenus('destroy');
```

I found an error:
Uncaught TypeError: Cannot read property 'css' of null(…)

**Comment by vadikom** [comment]
This is the correct code and works fine on the default demo page:

http://vadikom.github.io/smartmenus/src/demo/

So I guess there is something wrong on your page that causes the issue. Please post some kind of demo if you like and I can check it.
