### ISSUE TITLE
Dropdown menu doesn't work when using `display: flex`

### ISSUE THREAD

**Issue by wesruv** [vadikom/smartmenus#58]
I think I identified the issue: 
https://github.com/vadikom/smartmenus/blob/master/src/jquery.smartmenus.js#L425

Not sure what this code is used for, but if I change it to this it's working (in Chrome at least):
```
        return this.$firstLink.css('display') == 'block' || this.$firstLink.css('display') == 'flex';
```

I'm using flexbox on a bunch of top level menu elements to get everything equal height dynamically instead of hardcoding values.

**Comment by wesruv** [comment]
Even with that there are some positioning issues:
![image](https://cloud.githubusercontent.com/assets/5607236/21238397/e2bfca12-c2d0-11e6-90c2-6991370e4840.png)

Trying to figure out how that's calculated and why `display: flex` would mess with it.

**Comment by wesruv** [comment]
To be clearer, instead of the dropdown appearing below the parent link, it's over top of it, at 0,0. That's what that is a screenshot of

**Comment by vadikom** [comment]
Sorry for the delay! Yes, that line is used to detect whether CSS support is enabled in the browser at runtime. If you need to use `display: flex` for the main menu links, then, as you've figured, you would really need to edit that line - something like this should also work:
```javascript
return this.$firstLink.css('display') != 'inline';
```
As for the first-level sub menu positioning issue - it seems to happen if you apply `display: flex` to the main menu `<li>` elements too. To avoid the issue, you could use the following additional CSS:
```css
#main-menu > li > ul,
#main-menu > li > span.scroll-up,
#main-menu > li > span.scroll-down {
	top: 100% !important;
}
```

**Comment by wesruv** [comment]
No problem 😄 thanks for getting back to me.

I ended up using `transform: translate( ... )` to get the desired result, seems to be working well. 

Is this bit likely to go into the codebase:
```
return this.$firstLink.css('display') != 'inline';
```

We're using (and loving) smart menus in [Backdrop CMS](https://github.com/backdrop/backdrop) and I think that might be worth having in the long run. 

If not, no worries. I ran into this for a specific site, I think for the vast majority of the Backdrop's use case will be fine.

**Comment by vadikom** [comment]
Yep, I believe this is safer than the current code so I will change it in the next release. Thanks a lot for your feedback!

**Comment by vadikom** [comment]
Suggested change above is now committed 3385fdf

**Comment by wesruv** [comment]
Thanks!
