### ISSUE TITLE
not work in bootstrap rtl

### ISSUE THREAD

**Issue by vahidalvandi** [vadikom/smartmenus#61]
i convert core bootstrap ltr to rtl with gulp 

but submenu in smartmenu not work corectlly

![menu_smart](https://cloud.githubusercontent.com/assets/17952925/22161373/4c5f9e52-df5f-11e6-8ffa-6ba6dec43694.jpg)

**Comment by vahidalvandi** [comment]
when use it in original bootstrap work correctly

**Comment by vadikom** [comment]
Please post some kind of demo URL.
