### ISSUE TITLE
can't find

### ISSUE THREAD

**Issue by vahidalvandi** [vadikom/smartmenus#62]
in scss first line color theme 

@import 'compass';

// This file is best viewed with Tab size 4 code indentation

compass not exists

**Comment by vadikom** [comment]
Compass is used/required for some mixins in the themes (e.g. for cross-browser gradients, box-shadow, etc.) So you will need to install it in addition to SASS:

http://compass-style.org/install/
http://thesassway.com/beginner/getting-started-with-sass-and-compass
