### ISSUE TITLE
Bug: invalid import of main module in smartmenus-bootstrap

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [vadikom/smartmenus#66]
The main npm's module name (in _package.json_) is `smartmenus` so when I import `smartmenus-bootstrap` (bootstrap addon), I get:
```
ERROR in ./~/smartmenus-bootstrap/jquery.smartmenus.bootstrap.js
Module not found: Error: Can't resolve 'jquery.smartmenus' in '/tmp/tests/node_modules/smartmenus-bootstrap'
 @ ./~/smartmenus-bootstrap/jquery.smartmenus.bootstrap.js 14:2-50
 @ ./src/app.js
```

Workaround: add following code to _webpack.config.js_
```
resolve: {
    alias: {
        'jquery.smartmenus': 'smartmenus'
    }
}
```

But, you should change npm's module name to `jquery.smartmenus` or change `jquery.smartmenus` to `smartmenus` in _jquery.smartmenus.bootstrap.js_ line 14. Yes, you can use dot in module name like [jquery.cookie](https://www.npmjs.com/package/jquery.cookie).

**Comment by vadikom** [comment]
Thanks for the input! I guess changing the npm module's name at this point is not a good option so the fix in the addons is the way to go.

I will merge your fix and make a few more changes a bit later. Thanks again!

**Comment by dzwiedziu-nkg** [comment]
By the way, please visit: https://github.com/dzwiedziu-nkg/react-smartmenus-bootstrap-example :)
