### ISSUE TITLE
inline-block error.

### ISSUE THREAD

**Issue by Ryu-k** [vadikom/smartmenus#68]
Hello,

When the menu "a" tag are set as inline-block the script doesn't work.

structure of the menu : sm > ul > li > a
when the "a" are set as "display:block" the menu works perfectly, but when set on "inline-block" or other display mode it suddenly stop to work.

I need to be able to set the "a" as inline-block for the menu layout I am currently using.

Hope to hear back from you soon.

Regards

**Comment by vadikom** [comment]
Hi, this is a known issue in v1.0.1 that has been fixed in the master branch already. So until the official v1.0.2 is out, you could use the most recent development version to avoid the issue:

https://raw.githubusercontent.com/vadikom/smartmenus/master/src/jquery.smartmenus.js

**Comment by borys-p** [comment]
I just encountered the same problem. Do you have any estimate when 1.0.2 will be released and available via npm?
