### ISSUE TITLE
Vertical menu problem

### ISSUE THREAD

**Issue by Ryu-k** [vadikom/smartmenus#69]
Hello,

Currently my menu is structured like this : 
`<ul><li><a><span>ITEM NAME</span></a><ul><li>sub menu</li></lul><li></ul>`

The problem is that I can open the sub menu part when clicking on "ITEM NAME" but can't close it by re-clicking it, it seems that the <span> tag is creating the problem.

When removing the <span> it works well but I need it for additional styling.

Regards

**Comment by vadikom** [comment]
Hi,

This actually turned out to be a bug so I just fixed it d773d07aae004ec7b38c334759536a3f1b76ce19

You could use the latest dev version from here:

https://raw.githubusercontent.com/vadikom/smartmenus/master/src/jquery.smartmenus.js

until v1.0.2 is released.

Thanks!

**Comment by Ryu-k** [comment]
Awesome, thanks a lot!

I have noticed something else, I don't know if this is meant to be this way but in the vertical menu if you have a structure like this : 

`<ul><li>top item
     <ul><li>sub item
             <ul><li>sub sub item</li></ul>
     </li></ul>`
</li></ul>

If you click the "top item" it will open "sub item",
then if you click "sub item" it will open the "sub sub item".
But when you re-click "sub item" instead of hiding "sub sub item" it will close all the sub menu.

Again, thanks for the awesome plugin and really fast reply.

Hope you'll have a nice day!

Regards

**Comment by vadikom** [comment]
No problem at all!

It's not an issue - it's meant to function like that. In collapsible mode a first tap/click on a parent item displays its sub menu and a second tap activates the item's link and if `hideOnClick: true` (which is the case by default), then the menu tree is also reset when a link is activated.

Cheers!
