### ISSUE TITLE
Sub menu hiding problem

### ISSUE THREAD

**Issue by Ryu-k** [vadikom/smartmenus#70]
Hello, I have made a "Mega menu" and have a problem because the mega menu content is like this :  

```
<ul>
<li><a href="#"><span>Top item</span></a></li>
<li><a href="#"><span>Top item Megamenu</span></a>
<ul class="megamenu_dropdown">
<li ><a href="#"><span>First column</span></a>
	<ul  class="always_show">
		<li><a href="#"><span>Test 8</span></a></li>
		<li><a href="#"><span>Test 9</span></a></li>
	</ul>
</li>
<li ><a href="#"><span>Second column</span></a>
	<ul class="always_show">
		<li><a href="#"><span>Test 8</span></a></li>
		<li><a href="#"><span>Test 9</span></a></li>
	</ul>
</li>
<li ><a href="#"><span>Third column</span></a>
	<ul class="always_show">
		<li><a href="#"><span>Test 8</span></a></li>
		<li><a href="#"><span>Test 9</span></a></li>
	</ul>
</li>
</ul>
</li>
</ul>
```

The problem occurs when I add the css to always show the sub menu that are in the mega menu.

If I hove only the sub item of the same "ul", then the menu act correctly and detect when I leave the megamenu area and hide it, but if I hover the other "ul" of the megamenu the megamenu always stay on.

I there anyway to disable the sub menu that are in the megamenu area?

I joined a video of the problem.

Thanks in advance

Regards

[smartmenus.zip](https://github.com/vadikom/smartmenus/files/888247/smartmenus.zip)

PS : If you add the display:block!important to the sub menu this break the menu behavior. I know the source of the problem but don't know how to fix it, I need to have those sub menu always showing.

**Comment by vadikom** [comment]
Try adding the `mega-menu` class to the mega menu UL element like this:

```html
<ul class="megamenu_dropdown mega-menu">
```

and let me know if you still have any troubles. This class is required by the script for mega menus.

**Comment by Ryu-k** [comment]
Thanks a lot that did the trick!

I thought I carefully checked the documentation before asking this but seems that I missed that part.

Sorry for bothering and again thanks for the awesome plugin!

Have a nice day!

Regards
