### ISSUE TITLE
How to use custom options in smartmenus-bootstrap?

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [vadikom/smartmenus#71]
How to use custom options in smartmenus() function when I use smartmenus-bootstrap?

Currently I modify your code:
https://github.com/vadikom/smartmenus/blob/master/src/addons/bootstrap/jquery.smartmenus.bootstrap.js#L37
But it should be possible without modification of your library.

**Comment by vadikom** [comment]
You can use the `data-sm-options` attribute:

https://www.smartmenus.org/docs/#data-sm-options
