### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeClass' of undefined

### ISSUE THREAD

**Issue by gcatto** [vadikom/smartmenus#73]
After choosing an option from one smartmenu, once the user shows another smartmenu and hides it one way or another, I am getting:

```
Uncaught TypeError: Cannot read property 'removeClass' of undefined
    at $.SmartMenus.menuHide (jquery.smartmenus.js:597)
    at $.SmartMenus.menuHideAll (jquery.smartmenus.js:617)
    at $.SmartMenus.docClick (jquery.smartmenus.js:320)
    at HTMLDocument.proxy (jquery.js:497)
    at HTMLDocument.dispatch (jquery.js:4737)
    at HTMLDocument.elemData.handle (jquery.js:4549)
```

The line in question in smartmenus is:

```
// unhighlight parent item + accessibility
$sub.dataSM('parent-a').removeClass('highlighted').attr('aria-expanded', 'false');
```

Any ideas? Thanks!

**Comment by vadikom** [comment]
Hmm, not sure what it might be really. Do you have any test case URL?

**Comment by gcatto** [comment]
Figured it out and it was my problem, not yours! I was re-rendering something too early, which was remove an ancestor of the smartmenu from the DOM before the smartmenu "closed" itself, and that's what caused it all.

Sorry for the false positive!
