### ISSUE TITLE
Deafult carets do not disappear in mobile view

### ISSUE THREAD

**Issue by dave7777** [vadikom/smartmenus#74]
Hello!
Thank you for your fantastic product!!! I had a short question why the default carets do not disappear in mobile view. I have attached the snapshot of the mobile view:

<a href="http://tinypic.com?ref=2wnu177" target="_blank"><img src="http://i63.tinypic.com/2wnu177.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Thanks again!)
Dave

**Comment by vadikom** [comment]
Hi, not sure really, seem to be duplicated for some reason. :? If you like, please share a demo URL and I can check what might be wrong with your code. Thanks!

**Comment by vadikom** [comment]
Close due to inactivity.
