### ISSUE TITLE
Remove compass dependency

### ISSUE THREAD

**Issue by borys-p** [vadikom/smartmenus#79]
Compass-sass is a dead project and many other projects are moving forward without it. Smartmenus is using only one `box-shadow` mixin which [can be already used without prefixes](http://shouldiprefix.com/#box-shadow) (or you can add autoprefixer to the build process).

I had to manually remove `@include compass`. This will also make some people unable to use this library directly from npm.

**Comment by vadikom** [comment]
I agree and this will be done for the v1.1 release. It's currently used for a little bit more than `box-shadow` in some themes but, as you noted, it could all be done without compass nonetheless.

Actually we could argue the same about sass itself as many are moving away to PostCSS (and I have already for some projects) so it's most probably also going to be replaced but unlikely in v1.1.

**Comment by borys-p** [comment]
So.... when can we expect the next version? ;-)

**Comment by vadikom** [comment]
Should be very soon (I hope within two weeks). The only thing that is still not finished is the Bootstrap 4 addon. Since Bootstrap 4 has gone beta, I think it's time to release an addon for it and I'd like to do it with v1.1. So I really hope I can iron out the code within two weeks (although I've got other work to take care of too in the meantime).

**Comment by borys-p** [comment]
Great news, thanks for the info.

Did you think about moving Bootstrap addon into a separate project? It wouldn't block the main release and should be easier to make addons for other frameworks (Zurb Foundation for example).

**Comment by ronilaukkarinen** [comment]
I can probably help to build this in the near future, as I like to build all my scss from scratch.

**Comment by vadikom** [comment]
1.1.0 is done now and Compass dependency is removed in the themes.

I will consider making the addons separate projects - initially there were none available, then just one and now a growing number, so maybe it's really a good idea.

Cheers!
