### ISSUE TITLE
bootstrap addon - display: flex is crashing smartmenus in Chrome

### ISSUE THREAD

**Issue by theskyliner** [vadikom/smartmenus#80]
I applied ```display:flex;```  to the ```ul.navbar-nav```, after that the menu didn't collapse anymore on hover. Just on click.

I had to comment out the following line:
https://github.com/vadikom/smartmenus/blob/master/dist/addons/bootstrap/jquery.smartmenus.bootstrap.js#L96

And now I'm always returning false there, but for sure I dont like that kind of hack.
Could you please fix this?

It's only not working in Google Chrome. Firefox and Edge were fine.

Best Regards
Nick

**Comment by vadikom** [comment]
This has been fixed in the dev version some time ago:

https://github.com/vadikom/smartmenus/blob/master/src/addons/bootstrap/jquery.smartmenus.bootstrap.js

So please use it instead.

The fix will also be included in the upcoming v1.1.

Cheers!
