### ISSUE TITLE
Release 1.0.2 stable

### ISSUE THREAD

**Issue by qzminski** [vadikom/smartmenus#81]
Hey can you release 1.0.2 stable with the latest hotfixes? I've seen the last commit is from May and we would need the new version which contains the crucial fix for `display: flex` problem: https://github.com/vadikom/smartmenus/commit/3385fdfc4f56be6acdee260b8257ce97488ed9f1

**Comment by vadikom** [comment]
v1.1.0 is currently being prepared for release and I believe it will be ready by the end of this week. So please stay tuned. 1.0.2 will not happen but it will be very simple to upgrade to 1.1.0.

**Comment by vadikom** [comment]
OK, it's finally done, the npm packages are updated too.

Cheers!
