### ISSUE TITLE
Fixed-top Menu don't scroll by finger on small screens

### ISSUE THREAD

**Issue by Aharito** [vadikom/smartmenus#83]
Hi!

On small mobile screens (Android + Chrome), the fixed-top and fixed-bottom Bootstrap 4 menu (when expanded) **unable to scroll** with finger.

But for example static menu able to scroll.

![image](https://user-images.githubusercontent.com/6253807/31726178-6e27e474-b450-11e7-8297-93560c177bc3.png)
Thanks in advance

**Comment by vadikom** [comment]
Yes, this is an issue in Bootstrap 4.0.0 beta. I've reported it so hopefully it will be fixed in the next release:

https://github.com/twbs/bootstrap/issues/24260

**Comment by vadikom** [comment]
Bootstrap 4.5.0 still doesn't have this fixed. You can follow the progress and find some solutions here:

https://github.com/twbs/bootstrap/issues/23374
