### ISSUE TITLE
Bootstrap 4 beta.2 Mega Menu Alignment

### ISSUE THREAD

**Issue by ScotsScripts** [vadikom/smartmenus#84]
Mega Menu positioning and size appears to be broken in bootstrap 4 beta.2 - the mega menu opens at the left side of the page/navbar. 

Adding the 'dropdown' class to the list item moves the mega menu into position under the toggle however it's not wide - only the same width as a regular dropdown.

**Comment by SRTM** [comment]
Firstly, you'll need to use the bootstrap 4 addon.
https://github.com/vadikom/smartmenus-bootstrap-4

Secondly, smartmenus with the bootstrap 4 plugin doesn't have megamenu support yet - which I've requested here:
https://github.com/vadikom/smartmenus-bootstrap-4/issues/1

So you'll need to find another solution until then if you need a megamenu. I had to create a custom one.

**Comment by ScotsScripts** [comment]
I am using the bootstrap 4 addon exactly as in the bs4 example page. The toggle does not work properly.

Mega menu: that would explain it :)
