### ISSUE TITLE
A question about licensing conditions

### ISSUE THREAD

**Issue by MrPaulDriver** [vadikom/smartmenus#90]
I would like to include the community edition of smartmenus in a Drupal distribution aimed at schools.

As part of Drupal's licensing conditions, any third party resources [must be compatible](https://www.drupal.org/project/drupalorg_whitelist) with Drupal's GPL2 licence. 

Whilst smartmenus' MIT license is compatible, it appears that [shjs.js](https://github.com/vadikom/smartmenus/blob/master/src/libs/demo-assets/shjs/shjs.js), used in the demo assets, is licensed at GPL-3.0

I have raised [this issue](https://www.drupal.org/project/drupalorg_whitelist/issues/2995399) on www.drupal.org and a quick look will provide further background.

I would like to ask if it would be possible to change the licensing of this file, or otherwise make available a slimmed down version of the repo without the demo files?

Thank you

**Comment by vadikom** [comment]
Hi! Do you need this (potential) new repository to be installable/updatable via bower/npm? If not, why not simply grab a copy of the current repo and delete the "shjs" folder inside "demo-assets"? The SHJS script is used just for code highlighting on the demo pages.

**Comment by MrPaulDriver** [comment]
The reason we don't want to base our distribution on a copy with the "shjs"-folder deleted is because we don't want to create a fork. Instead, we want to automatically build the distribution by pulling in your github repo with a make-file in a similar way to bower or npm. Our reason for preferring not to fork, is that it might break the chain of update communication.

**Comment by vadikom** [comment]
Sorry for the delay! It's been very busy times here lately.

I've now removed the SHJS source code from the repo so I guess this solves the issue for you. It's now loaded externally and if that fails for some reason the code samples on the demo pages will just not be highlighted which is not a huge issue.
