### ISSUE TITLE
Proposal for main menu

### ISSUE THREAD

**Issue by gtbu** [vadikom/smartmenus#91]
I have to add id="main-menu" to the first ul . 
But there is 
< ul class="sm sm-blue" id="sm-15361390927628298-2" role="group" aria-hidden="true" aria-labelledby="sm-15361390927628298-1" aria-expanded="false">

The code which adds  id="sm-15361390927628298-2" could also add  id="main-menu" automatically. This is easier for implementation in a CMS .

**Comment by vadikom** [comment]
You don't have to add the 'main-menu' class to the root `<ul>` element if you don't want to. It's just used in the demos to target the menu list element when initializing it:

`$('#main-menu').smartmenus( ...`

However, neither the script, nor the CSS requires that id and if you like, you could target the `<ul>` element in other ways:

`$('.sm')`
`$('#navbar ul')`

etc. whatever you like and works in your case.
